### ISSUE TITLE
有的歌曲无法正确解析 url

### ISSUE THREAD

**Issue by aoestone** [xizeyoupan/MetingJS#1]
作者你好，偶然发现有的腾讯系歌曲无法正确解析 url，例如：

```html
<meting-js auto="https://y.qq.com/n/yqq/song/000Vb13F0Pf2Y5.html"></meting-js>
```

![image](https://github.com/xizeyoupan/MetingJS/assets/143681838/6bf91fd8-25fb-4312-b9fb-601044b2f47e)

![image](https://github.com/xizeyoupan/MetingJS/assets/143681838/6177de99-ca70-46f9-926a-c68581af42ba)

**Comment by xizeyoupan** [comment]
https://github.com/xizeyoupan/MetingJS/commit/da6d93b1421f742b520e7b7e609dbaf45ebb5d1e
